spin_manifest_version = 2

[application]
name = "weather-new"
version = "0.1.0"
authors = ["Corey Ryan <corey@coreyr.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "weather-new"

[component.weather-new]
source = "target/wasm32-wasip1/release/weather_new.wasm"
allowed_outbound_hosts = []
[component.weather-new.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
