spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[variables]
tool_components = { default = "" }
# ========================================
# Available auth provider configurations
# ========================================

# AuthKit:
# {
#   "type": "authkit",
#   "issuer": "https://your-tenant.authkit.app",
#   "audience": "mcp-api"  // optional
# }

# Generic OIDC (Auth0, Keycloak, etc):
# {
#   "type": "oidc",
#   "name": "auth0",
#   "issuer": "https://your-domain.auth0.com",
#   "jwks_uri": "https://your-domain.auth0.com/.well-known/jwks.json",
#   "authorization_endpoint": "https://your-domain.auth0.com/authorize",
#   "token_endpoint": "https://your-domain.auth0.com/oauth/token",
#   "userinfo_endpoint": "https://your-domain.auth0.com/userinfo",  // optional
#   "audience": "your-api-identifier",  // optional
#   "allowed_domains": ["*.auth0.com"]  // optional
# }
#
# Auth gateway configuration - auth is DISABLED by default
# To enable auth, set SPIN_VARIABLE_AUTH_CONFIG with your auth configuration or edit the block below.
auth_config = { default = '''
{
  "mcp_gateway_url": "http://ftl-mcp-gateway.spin.internal/mcp-internal",
  "trace_id_header": "X-Trace-Id",
  "enabled": false,
  "providers": [
    {
      "type": "authkit",
      "issuer": "https://your-tenant.authkit.app"
    }
  ]
}
''' }

# Auth Gateway - handles authentication and OAuth discovery
[[trigger.http]]
route = "/mcp"
component = "mcp"

[[trigger.http]]
route = "/.well-known/oauth-protected-resource"
component = "mcp"

[[trigger.http]]
route = "/.well-known/oauth-authorization-server"
component = "mcp"

[component.mcp]
source = { registry = "ghcr.io", package = "fastertools:ftl-auth-gateway", version = "0.0.4" }
allowed_outbound_hosts = ["http://*.spin.internal", "https://*.authkit.app"]
[component.mcp.variables]
auth_config = "{% raw %}{{ auth_config }}{% endraw %}"

# MCP Gateway - internal endpoint (protected by auth gateway)
[[trigger.http]]
route = { private = true }
component = "ftl-mcp-gateway"

[component.ftl-mcp-gateway]
source = { registry = "ghcr.io", package = "fastertools:ftl-mcp-gateway", version = "0.0.3" }
allowed_outbound_hosts = ["http://*.spin.internal"]
[component.ftl-mcp-gateway.variables]
tool_components = "{% raw %}{{ tool_components }}{% endraw %}"
validate_arguments = "true"