spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[variables]
tool_components = { default = "" }
auth_config = { default = '''
{
  "mcp_gateway_url": "http://ftl-mcp-gateway.spin.internal/mcp-internal",
  "trace_id_header": "X-Trace-Id",
  "enabled": false,
  "providers": []
}
''' }

# Auth Gateway - handles authentication and OAuth discovery
[[trigger.http]]
route = "/mcp"
component = "mcp"

[[trigger.http]]
route = "/.well-known/oauth-protected-resource"
component = "mcp"

[[trigger.http]]
route = "/.well-known/oauth-authorization-server"
component = "mcp"

[component.mcp]
source = { registry = "ghcr.io", package = "fastertools:ftl-auth-gateway", version = "0.0.4" }
allowed_outbound_hosts = ["http://*.spin.internal", "https://*.authkit.app"]
[component.mcp.variables]
auth_config = "{% raw %}{{ auth_config }}{% endraw %}"

# MCP Gateway - internal endpoint (protected by auth gateway)
[[trigger.http]]
route = { private = true }
component = "ftl-mcp-gateway"

[component.ftl-mcp-gateway]
source = { registry = "ghcr.io", package = "fastertools:ftl-mcp-gateway", version = "0.0.3" }
allowed_outbound_hosts = ["http://*.spin.internal"]
[component.ftl-mcp-gateway.variables]
tool_components = "{% raw %}{{ tool_components }}{% endraw %}"
validate_arguments = "true"