spin_manifest_version = 2

[application]
name = "mcp-components"
version = "0.1.0"
authors = ["bowlofarugula <bowlofarugula@gmail.com>"]
description = "MCP gateway with tool components"

[[trigger.http]]
route = "/mcp"
component = "mcp-gateway"

# Test endpoints to verify components work
[[trigger.http]]
route = "/test/tools-list"
component = "tools-list"

[[trigger.http]]
route = "/test/echo"
component = "echo"

[[trigger.http]]
route = "/test/add"
component = "add"

[component.mcp-gateway]
source = "mcp-gateway/target/wasm32-wasip1/release/mcp_gateway.wasm"
allowed_outbound_hosts = ["http://*.spin.internal"]
[component.mcp-gateway.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "mcp-gateway"
watch = ["src/**/*.rs", "Cargo.toml"]

# Internal components (not exposed via HTTP triggers)
[component.tools-list]
source = "tools-list/target/wasm32-wasip1/release/tools_list.wasm"
allowed_outbound_hosts = []
[component.tools-list.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools-list"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.echo]
source = "echo/target/wasm32-wasip1/release/echo.wasm"
allowed_outbound_hosts = []
[component.echo.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "echo"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.add]
source = "add/target/wasm32-wasip1/release/add.wasm"
allowed_outbound_hosts = []
[component.add.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "add"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "echo-js"

[component.echo-js]
source = "echo-js/dist/echo-js.wasm"
allowed_outbound_hosts = []
[component.echo-js.build]
command = "npm install && npm run build"
workdir = "echo-js"
