spin_manifest_version = 2

[application]
name = "gateway-demo"
version = "0.0.1"
authors = ["bowlofarugula <bowlofarugula@gmail.com>"]
description = "MCP gateway with tool components"

[variables]
tool_components = { default = "echo,add,echo-js,image-demo" }

[[trigger.http]]
route = "/mcp"
component = "ftl-mcp-gateway"

# Test endpoints to verify components work
[[trigger.http]]
route = "/test/echo"
component = "echo"

[[trigger.http]]
route = "/test/add"
component = "add"

[component.ftl-mcp-gateway]
source = { registry = "ghcr.io", package = "fastertools:ftl-mcp-gateway", version = "0.0.1" }
allowed_outbound_hosts = ["http://*.spin.internal"]
[component.ftl-mcp-gateway.variables]
tool_components = "{{ tool_components }}"

# Internal components (not exposed via HTTP triggers)
[component.echo]
source = "echo/target/wasm32-wasip1/release/echo.wasm"
allowed_outbound_hosts = []
[component.echo.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "echo"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.add]
source = "add/target/wasm32-wasip1/release/add.wasm"
allowed_outbound_hosts = []
[component.add.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "add"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "echo-js"

[component.echo-js]
source = "echo-js/dist/echo-js.wasm"
allowed_outbound_hosts = []
[component.echo-js.build]
command = "npm install && npm run build"
workdir = "echo-js"

# Test endpoint for image demo
[[trigger.http]]
route = "/test/image-demo"
component = "image-demo"

[component.image-demo]
source = "image-demo/target/wasm32-wasip1/release/image_demo.wasm"
allowed_outbound_hosts = []
[component.image-demo.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "image-demo"
watch = ["src/**/*.rs", "Cargo.toml"]
